### ISSUE TITLE
Automatically detect directory in page name

### ISSUE THREAD

**Issue by jamieoliver** [gollum/gollum-lib#11]
As per discussion in #10. The separate directory parameter in various methods should be removed and automatically detected in the page name. This will need to be done sympathetically so as to minimise the impact on existing code.

**Comment by gerwitz** [comment]
Thankfully, there's nothing to prevent an app built with gollum-lib from ignoring the directory parameter. So we faked this behavior in [rails-wiki](https://github.com/TheArtificial/rails-wiki).

**Comment by dometto** [comment]
#216 will help with this.

**Comment by dometto** [comment]
This has been implemented in #322 and #326 -- will be released in 5.x
