### ISSUE TITLE
Code block not correctly escaped when using pygments

### ISSUE THREAD

**Issue by techwiz24** [gollum/gollum-lib#154]
Putting 

    
    ```bash
    sudo patch -p1 < ~/auth.patch
    ```
    
in a markdown file causes the remainder of the document to be rendered inside of a `<pre>` tag. Removing the `<` character from the code block corrects the problem. This problem is not encountered if `pygments.rb` is not installed.

**Comment by mchill** [comment]
[This line](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/code.rb#L76) appears to be the culprit. I honestly can't see a reason for taking a different path on `nil` or `"bash"`. If that differentiation has to stay, though, `code` needs to be passed through a function to encode HTML special characters.

**Comment by dometto** [comment]
I dont see the point of filtering out bash either, since pygments supports it. Maybe lang needs to be non-nil though? @bartkamphorst?

**Comment by techwiz24** [comment]
@dometto The lang does need to be non-`nill` ***and*** [a language that `pygments.rb` recognizes](https://github.com/gollum/gollum-lib/pull/157) I believe, which is why we default to `text` if one cannot be found.

Regardless, the line mentioned by @mchill still needs to be HTML-Escaped. I'll do some testing today and see if I can't get a PR written up.

**Comment by bartkamphorst** [comment]
Not sure what the reasons were to put bash syntax between pre-tags. And yes, lang indeed has to be non-nil. Thanks @techwiz24 for offering to work on this!
