### ISSUE TITLE
Fix failing test "cannot revert conflicting commit" on JRuby

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum-lib#156]
See [Travis CI](https://travis-ci.org/gollum/gollum-lib/jobs/63777683).

**Comment by dometto** [comment]
Fixed by https://github.com/repotag/gollum-lib_rjgit_adapter/commit/ae7b56a031844702dedde4488aeb363e0db6adcd

**Comment by bartkamphorst** [comment]
Sweet. :+1:
