### ISSUE TITLE
Better Search

### ISSUE THREAD

**Issue by Naatan** [gollum/gollum-lib#166]
At the moment search returns page names and number of matches, this makes finding what you're looking for still rather painful. It would be much better if it could return the actual matched content.

I understand this is probably a challenge because you don't want to be returning the raw source to the end user, and if you cut out a line it may not parse properly if you want to attempt to convert it to html. It's a challenge but imo it's one that'll need to be overcome.

**Comment by dometto** [comment]
> I understand this is probably a challenge because you don't want to be returning the raw source to the end user, and if you cut out a line it may not parse properly if you want to attempt to convert it to html. It's a challenge but imo it's one that'll need to be overcome.

The current approach (#343) will return raw source to the end user and HTML escape it (one line of context). Given that the user is searching through markup source documents (and possibly searching *for* an expression containing markup), I think it would be unnecessary and unexpected to render the search context.

**Comment by dometto** [comment]
Resolved in #343
