### ISSUE TITLE
AsciiDoc h3 headers are broken

### ISSUE THREAD

**Issue by mchill** [gollum/gollum-lib#171]
First off, sorry for the onslaught of AsciiDoc-related Issues...

Asciidoctor includes backwards compatibility with old AsciiDoc headers. Unfortunately, kramdown-style code blocks use conflicting syntax, so this will break rendering.

```
Header
~~~~~~ // should become an h3 header
```

(Even more fun, I just discovered that using kramdown-style code block syntax inside of GFM code blocks breaks GitHub comments. -.-)

I propose simply [turning off](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/code.rb#L25) kramdown-style code blocks when `@markup.format == :asciidoc`. Any objections?

**Comment by bartkamphorst** [comment]
Actually, this header snippet by itself does not match the code block [regexp](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/filter/code.rb#L25); only when there is a second h3 header present will there be a match. Regardless, there are a couple of solutions imaginable here. One is to indeed disable these types of code blocks for asciidoc specifically. Another is to disable these types of code blocks altogether except for markdown. And a third is to change the regexp to expect a newline (`\n`) before the code block. That way, we could differentiate between a header and a code block, but I'm not sure how that would sit with certain markup specs. Whatever we decide, it will most likely break some people's wikis. Any thoughts and/or preferences, @mchill @sunny @dometto ?

**Comment by dometto** [comment]
I think there's even an argument to be made to just get rid of the gollum-specific codeblocks altogether. That would greatly simplify maintenance and potentially improve performance a lot. The main reason for keeping them was github compatibility, but arguably that's not a reason any longer. Alternatively we could keep them for markdown only, to better mimic github-markdown.

**Comment by bartkamphorst** [comment]
I think it's still the objective to stay as close to github's behavior as possible. I've given the issue some thought, and I think we should just make the fenced code blocks with `~~~` specific to markdown. That solves this issue, and keeps fenced code blocks with backticks available in all markups.

**Comment by dometto** [comment]
Fine for now, but there's still a more fundamental debate to be had about whether it makes sense to add gollum's own code block syntax to markups which already have their own code block syntax (or not, for good reason). I *think* github also doesn't support backtick-blocks in markups other than markdown (but I may be wrong about this).

**Comment by dometto** [comment]
(Although there is the issue of syntax highlighting, which some markupsl gens might not support themselves)

**Comment by bartkamphorst** [comment]
That's exactly why I think we should keep the backticks. :)

**Comment by bartkamphorst** [comment]
@mchill This should be fixed on master.
