### ISSUE TITLE
two Makros, I use

### ISSUE THREAD

**Issue by bpieck** [gollum/gollum-lib#173]
Since you asked to know about Makros we write ourself:
I use for now a Preview(<page-name>) Makro, to render a Preview for another side (can be used for example as article of the day). And a second "statistics" Makro, the generates an ul with last updated page, last created page, and number of all pages.

If one or both of them are interesting for you, I would of course create a fork and pull request.

**Comment by rgroux** [comment]
@bpieck 

:+1:

**Comment by bartkamphorst** [comment]
Yes, we'd be open for Makro PRs. I'm not entirely clear on what the Preview Makro would do, but I like the idea of a statistics page! I'll close this issue though as it's not really an issue, but feel free to open PRs when you are ready.
