### ISSUE TITLE
renaming problems with page-file-dir set

### ISSUE THREAD

**Issue by mpnowacki** [gollum/gollum-lib#175]
There is a problem with renaming files (that includes changing wiki format) with page-file-dir set. I described the problem here: https://github.com/gollum/gollum/issues/1076.
The problem is in `wiki.rb` in functions `rename_page` and `update_page`, namely in the input args for `commiter.add_to_index` calls. `add_to_index` internally adds the `@page_file_dir` (unlike `commit.add`), but the paths supplied in the input contain `page_file_dir`. I've solved it, probably in a dirty way, since today was my first day of doing anything in ruby, and set up a pull request https://github.com/gollum/gollum-lib/pull/174

**Comment by dometto** [comment]
This was already solved in #174
