### ISSUE TITLE
Support conventional markdown hyperlinks

### ISSUE THREAD

**Issue by Naatan** [gollum/gollum-lib#177]
I don't really understand why gollum is forcing custom hyperlink styles, why not just use the conventional ones and infer your Wiki capabilities from them? Using custom markup somewhat defeats the purpose of using a standardized format.

**Comment by bartkamphorst** [comment]
Which styles exactly were you referring to? I always use the []() syntax for hyperlinks and that seems to work fine.

**Comment by Naatan** [comment]
They work fine but they do not work as Wiki hyperlinks. Wiki hyperlinks have additional functionality (eg. automatic relative mapping), indicators whether a page exists.

**Comment by dometto** [comment]
So you're referring to the `[[links]]` I guess. I also think it should be possible to do without those.

**Comment by dometto** [comment]
The problem with this would actually be that we would have to extract regular markdown links, and regular Mediawiki links, and so on for each supported markup format, and handle them ourselves (i.e. detect whether the link references a valid page), which we can't/shouldn't do. I understand that the gollum tags don't play well with other markdown tools, but the alternative is just to use markdown links without the special gollum goodies.

(An alternative would be to stop using gollum tags completely, and implement the "page present or absent" logic in JavaScript in gollum)

**Comment by dometto** [comment]
Closing this for above mentioned reasons. In version `5.x` you will also be able to disable gollum tags entirely on a per-markup basis, [like this](https://github.com/gollum/gollum-lib/blob/gollum-lib-5.x/lib/gollum-lib/markups.rb#L55).
