### ISSUE TITLE
`test-unit` development dependency not declared

### ISSUE THREAD

**Issue by jhominal** [gollum/gollum-lib#178]
As the `test/unit` header is not present in some Ruby implementations (e.g., [MRI 2.2.0+](https://bugs.ruby-lang.org/issues/9711)), the `test-unit` gem is necessary to run the tests of `gollum-lib`, but the development dependency is not declared.

I would make the pull request, but I do not know how you like to order the dependencies in the gemfile, and I am not sure what versions constraints to use.

**Comment by techwiz24** [comment]
This affects [JRuby installations](https://github.com/gollum/gollum/issues/1044) and the one that comes with arch as well.

**Comment by bartkamphorst** [comment]
I would think that `v.3.1.5` should work on all supported rubies, or does that cause trouble for 1.9.3? Anyway, you could insert the dependency in `gemspec.rb` at line 45 (just above `minitest-reporters`).
