### ISSUE TITLE
Move adapter dependency to gollum

### ISSUE THREAD

**Issue by gerwitz** [gollum/gollum-lib#180]
I'm using the Rugged adapter for an internal project, and it's going well.

But the gemspec hardcodes the default adapter as a dependency, which means bundler insists on installing the grit adapter, which in turn requires charlock_holmes, which is a [PITA to deploy to Heroku](http://tooky.co.uk/using-charklock_holmes-on-heroku/).

I'd love to move the grit_adapter dependency to Gollum's Gemfile.

**Comment by bartkamphorst** [comment]
> which in turn requires charlock_holmes, which is a PITA to deploy to Heroku.

Having encountered `charlock_holmes` issues many times myself, I feel your pain.

> I'd love to move the grit_adapter dependency to Gollum's Gemfile.

The problem with that is that it prevents gollum from working out of the box with `gem install gollum`. We do plan on swapping the default adapter at some point, but for that to happen we need to be more confident that the rugged adapter performs well enough. @jhominal is doing some excellent work currently to help us get there, but any help testing and/or patching the rugged adapter is very welcome!

**Comment by gerwitz** [comment]
I've been testing it and am completely satisfied with the rugged adapter.

So much so, that I'm considering removing my dependency on gollum-lib and using only the adapter directly!

**Comment by bartkamphorst** [comment]
Sorry for the long wait. Yes, a temporary fork is probably best for now. Development is slow at the moment, so I wouldn't want you waiting any longer on this change. We'll keep this issue open as a request to change the default adapter to rugged instead of removing it altogether, if that's okay with you.

**Comment by gerwitz** [comment]
If the intention of the dependency is to ensure `gem install gollum` works, perhaps the adapter should be referenced not by gollum's Gemfile (as I suggested) but by its gemspec?

**Comment by bartkamphorst** [comment]
This is currently blocked on https://github.com/gollum/rugged_adapter/issues/15.

**Comment by gerwitz** [comment]
I agree with the sentiment over there that the rugged adapter isn't ready to become the default.

But I'm going to keep beating my drum of "as a gollum-lib user I shouldn't have a dependency on grit only because the flagship user, gollum, requires it."

**Comment by dometto** [comment]
@gerwitz, ideally we would indeed chuck the grit dependency. But as far as I can see there's no way of doing that which still makes it possible to `gem install gollum` and get a working installation, so that's a dealbreaker. The gem system makes it really difficult to do something like this, since there just is no way to specify dependencies on a per-platform basis (there is in Gemfiles, but those aren't  consulted by rubygems when calculating dependencies).

**Comment by bartkamphorst** [comment]
@dometto The suggestion is not to _remove_ the dependency, but rather to _move_ the adapter dependency away from `gollum-lib` and to `gollum` itself. Do you see any reason why that couldn't work, given that we would use the same sort of gemspec trickery as we now have in `gollum-lib`?

**Comment by dometto** [comment]
Ah, that's an option. In that case we would have to release a separate Java version of gollum as well as of gollum-lib, but I think that could work.

**Comment by KHN190** [comment]
Hi. How to set gollum-lib to use rugged? This worked for gollum but not gollum-lib:
```
Parameters: {"utf8"=>"✓", "authenticity_token"=>"mMo/h/NxDKCywgYaBp1zaIlNkx5AEgVe9XJfCIC8Dfwd+8ue9U3XXUlsVZYt4/kuguYaurIhYYs0qoeg6nGWNA==", "wiki"=>{"name"=>"中文页面", "raw_data"=>"中文页面"}, "commit"=>"save"}
```
I appended the module to `application.rb`'s end:
```
# application.rb
module Gollum
  Gollum::GIT_ADAPTER = "rugged"
end
```
And in console checked:
```
rails console
> Gollum::GIT_ADAPTER
=> "rugged"
```
But in logger it still shows it's using grit:
```
Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT:
  gitlab-grit (2.7.3) lib/grit/index.rb:176:in `block in write_tree'
  gitlab-grit (2.7.3) lib/grit/index.rb:171:in `write_tree'
  gitlab-grit (2.7.3) lib/grit/index.rb:123:in `commit'
# ...
```

**Comment by KHN190** [comment]
@gerwitz Hi guys, I updated gollum-lib to use rugged as default: 
- https://github.com/KHN190/gollum-lib/blob/master/lib/gollum-lib.rb#L8
- https://github.com/KHN190/gollum-lib/blob/master/gollum-lib.gemspec#L3

Worked for me. Have a check.

**Comment by gerwitz** [comment]
@KHN190: In my private fork for deployment I simply removed the dependancy from the gemspec. Very bunt and simple, but cannot be pulled into this repo until gollum proper handles it.

**Comment by KHN190** [comment]
Thank you, :) I've figured out a similar solution. Simply changed a fork of gollum-lib.Cheers.

Date: Tue, 19 Apr 2016 06:00:02 -0700

**Comment by dometto** [comment]
We won't be able to implement this before we release 5.x

**Comment by gerwitz** [comment]
Is 5.0 to be the last release, ever? A future milestone would be more comforting than a closure.

**Comment by dometto** [comment]
@gerwitz we're planning to get rid of the grit adapter in 5.0. I assumed that would solve the issue. If I misunderstood I'll reopen!

**Comment by gerwitz** [comment]
Ah, indeed that fixes my reason for this issue, at least!
