### ISSUE TITLE
enhancement: Jumly graphs

### ISSUE THREAD

**Issue by rgroux** [gollum/gollum-lib#186]
can we use jumly with gollum in a filter? like we use plantuml and wsd.

with a local or a remote server.

actualy i have a personal macro fot this feature, but i can create a filter or a macro.

IMO  filter is a better choice.

http://jumly.tmtk.net/

like this

![image](https://cloud.githubusercontent.com/assets/13436563/11568361/de93ab48-99eb-11e5-952d-9d2e876a77ce.png)

**Comment by dometto** [comment]
We've just changed to PlantUML as the default on 5.x and dont want to support multiple UML solutions in order to ease maintenance. If you want to write your own filter for it I would be glad to include it in a contrib directory though.
