### ISSUE TITLE
github-markup 1.3.3 has expired.

### ISSUE THREAD

**Issue by leyafo** [gollum/gollum-lib#191]
'github-markup' 1.3.3 has expired，because 1.3.3's dependency gem 'asciidoctor'  version is  0.1.4. It was more than two years past the expiration. please upgrade 'github-markup' to 1.4.0.

see this link:
https://github.com/github/markup/pull/427

Thanks, If need any help, I'll glad to help.

**Comment by leyafo** [comment]
thanks.

**Comment by bartkamphorst** [comment]
No problem. :+1:
