### ISSUE TITLE
consider relaxing version requirement to ~> x.y for github-markup

### ISSUE THREAD

**Issue by pravi** [gollum/gollum-lib#206]
I'm packaging gitlab for debian and gollum lib is a dependency. We keep only one version of a gem in the archive and currently we have github-markup 1.4.0 and gollum-lib 4.1.0. Even though we have a newer minor release available in the archive, it is causing gitlab install to fail because the dependency is too strict. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821821

Can this be changed to ~> 1.3 (or ~> 1.4 for newer versions)? We could update to gollum-lib 4.2.0 right now, but the same problem will reappear when a newer github-markup minor release is uploaded.

**Comment by bartkamphorst** [comment]
I think `~> 1.4` instead of `~> 1.4.0` is probably fine. @dometto ?

**Comment by dometto** [comment]
Yes. I would say it should also be possible to backport a more relaxed 1.3 dependency, but I need to look and see if there was a reason for the strict dependency in the first case.

**Comment by pravi** [comment]
@dometto ~> 1.4 should be enough for my case as I updated to gollum-lib 4.2
