### ISSUE TITLE
Release of 4.3.0 on RubyGems?

### ISSUE THREAD

**Issue by connorshea** [gollum/gollum-lib#208]
Hey! I wanted to ask about releasing the latest master on RubyGems.

We're currently blocked from updating to Rouge 2.0 in GitLab because of gollum (https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4691), so I figured it was worth a shot. We don't technically need it for a few weeks, so don't worry about getting it out _right this second_ or anything, whenever you have time :)

Best,
Connor Shea

**Comment by bartkamphorst** [comment]
@dometto Would you have time to cut a release in the upcoming days? We can include emoji support on the next release.

**Comment by connorshea** [comment]
@bartkamphorst to be clear, you mean a new release of gollum-lib? If so, gladly :)

**Comment by bartkamphorst** [comment]
Yes.

**Comment by connorshea** [comment]
Oh, sorry, I thought you were asking me! Derp.

**Comment by connorshea** [comment]
4.2.1 is release now, so this can be closed 👍
