### ISSUE TITLE
update/relax stringex dependency

### ISSUE THREAD

**Issue by pravi** [gollum/gollum-lib#209]
Can you update/relax stringex dependency to ~> 2.6? debian already has stringex 2.6.0 and this will help us in packaging.

**Comment by pravi** [comment]
They follow SemVer https://github.com/rsl/stringex/issues/188

**Comment by dometto** [comment]
No objections in principle, but will have to see if tests pass on 2.6.

**Comment by dometto** [comment]
Closed in #211. Sorry for the wait. Will release a bump release somewhere today.
