### ISSUE TITLE
I wrote a maybe better Global TOC Macro, feedback requested

### ISSUE THREAD

**Issue by PeteMichaud** [gollum/gollum-lib#210]
https://gist.github.com/PeteMichaud/dca1f5831c98d8fc18821cb4164d2b67

The GlobalTOC macro just makes a flat list of pages that have the full path as the link text. It's pretty ugly, but it's also fairly cheap to process.

NestedTOC created a nested list of pages, according to the wiki structure, and it respects the h1_titles option. It's prettier, but also heavier.

The code works, but there are parts that are questionable-- I made notes in the comments about those things. If the code gets banged into reasonable shape, I'd be happy to submit a pull request so NestedTOC is in the default package for people who want a prettier TOC out of the box.

**Comment by PeteMichaud** [comment]
I just noticed, I probably put this on the wrong issues list--should I move this from gollum-lib to gollum?

**Comment by Agilus** [comment]
I think this is the right place.  The code for GlobalTOC() is in this project.

**Comment by dometto** [comment]
This post is fine in this issue tracker. I like the idea of a nested TOC macro, but at the moment we're in the process of a major refactor for gollum `5.x`. This will likely also involve changes in the generation of titles (with/out the `h1_titles` option) and the detection of header nodes. See e.g. https://github.com/gollum/gollum/issues/1177. So at this time, a PR for this `Macro` would complicate development too much. Please check back in a couple of months if you're still interested in getting this merged!
