### ISSUE TITLE
Broken _sidebar.md

### ISSUE THREAD

**Issue by toonetown** [gollum/gollum-lib#214]
With the changes from PR #198 , files named `_sidebar.md` no longer load (They need to be named `_Sidebar.md` - case-sensitive to load correctly with the changes).  That is a minor issue - but breaks previous functionality.

Also - subdirectories do not load the correct `_Sidebar.md`.  For example, given the following structure:

 * root
    * index.md
    * _Sidebar.md
    * subdir
        * index.md
        * _Sidebar.md

If you load `index.md`, the top-level `_Sidebar.md` is loaded.  However, if you load `subdir/index.md`, the top-level `_Sidebar.md` is still loaded.

I narrowed it down to commit 2fb3bea by rolling back one commit at a time between version 2.4.0 and 2.4.1 of `gollum-lib`.

I, personally, haven't noticed a huge improvement in page load time with #198 added - and it just breaks these cases.  Perhaps it could be rolled back?

**Comment by toonetown** [comment]
At the very least, I would suggest that a change that breaks previously-working sites (such as this) should be in a minor (2.x) upgrade...and not a bug fix (2.4.x) update.

**Comment by dometto** [comment]
Thanks for reporting this, @toonetown . You're right that this should not have been a patch but a major upgrade.  Sorry about that, this kind of stuff happens because we're rather swamped and still try to work on substantive issues in gollum and gollum-lib. @bartkamphorst: presumably we can still keep the performance improvements while keeping the old behavior?

**Comment by dometto** [comment]
As a side note, the improvements in #198 are maybe not so noticeable on smaller repos (in terms of number of files and commits), but become substantial for large repositories. See https://github.com/gollum/gollum/issues/1078. So we definitely don't want to just rollback those changes.

**Comment by bartkamphorst** [comment]
> You're right that this should not have been a patch but a major upgrade.

I apologize for unintentionally introducing breaking changes. I do think the decision to make it part of a patch release was fine, given that the regression tests all passed. I'll work on extending the test suite and fixing the lookup behavior.

**Comment by dometto** [comment]
> I do think the decision to make it part of a patch release was fine, given that the regression tests all passed.

Good point. :) @toonetown, looks like the solution will be to do a new patch re-instating the correct behavior. We'll try to do it fast.

**Comment by bartkamphorst** [comment]
I can at least confirm the behavior.

**Comment by bartkamphorst** [comment]
Any comments on [this PR](https://github.com/gollum/gollum-lib/pull/215), @dometto ?
