### ISSUE TITLE
Move lib/gollum-lib/file_view.rb to gollum

### ISSUE THREAD

**Issue by bartkamphorst** [gollum/gollum-lib#217]
It makes more sense to have the file view code live in the gollum code base, given that it is concerned with HTML.

**Comment by bartkamphorst** [comment]
It also needs to be rewritten because it uses hardcoded slashes for path handling (which breaks on Windows).

**Comment by bartkamphorst** [comment]
Gollum already has a `FileView` class: `Precious::Views::FileView` (which is a child of `Layout`). I wonder if the `Gollum::FileView` class from `gollum-lib` could be integrated.

**Comment by bartkamphorst** [comment]
A straightforward copy requires the following:
* Copying the Gollum::FileView code
* Loading the Gollum::FileView code inside Gollum
* Moving directory `test/file_view`
* Copying helper methods `normalize_html(text)` and `assert_html_equal(expected, actual, msg = nil)`
* Adding development dependency `nokogiri-diff`

I'm not so sure about the desirability of the last two points. Thoughts, @dometto, @maarten  ?

**Comment by maarten** [comment]
I don't mind copying the helper methods, the question is even whether an html normalize test helper should be necessary in gollum-lib. It makes me wonder what code uses that as it apparently is emitting html in that case, which shouldn't happen in this code to begin with.

Adding a development dependency is ok for me.

**Comment by dometto** [comment]
The normalize test helper is mainly for the tests relating to markup rendering. The rendering methods do spit html, and the normalize method helps to account for minor differences in the html output on different platforms (jruby vs MRI) and when using different versions  of (markdown) rendering gems.

**Comment by dometto** [comment]
> I'm not so sure about the desirability of the last two points.

To come back to this, I'm not against that if `nokogiri-diff` is available for `jruby`.

**Comment by bartkamphorst** [comment]
👍 We'll keep it on the todo list then for 5.x.

**Comment by dometto** [comment]
👍 I have some serious suggestions for refactoring, but it would be best to move the view first and keep the tests passing.

**Comment by bartkamphorst** [comment]
Agreed.
