### ISSUE TITLE
subpages not support macro

### ISSUE THREAD

**Issue by cloudchou** [gollum/gollum-lib#219]
I want to display all pages in sidebar . so I wrote this in _Sidebar.md:

```
# AllPages
<<AllPages()>>
```

But it can not display in side bar.  I test it in pages. it's ok.

So I  check the code .   And  found that the filter chain doesn't contain Macro chain in markup.rb. 
So I  add the macro chain. But it doesn't work too.  
althougth  it  will use the macro code. but it can not get all pages.

**Comment by dometto** [comment]
This should be fixed with the release of `v4.2.2`. Please let us know otherwise.
