### ISSUE TITLE
Internal links with slashes not converted to hyphens.

### ISSUE THREAD

**Issue by bsdfirst** [gollum/gollum-lib#223]
Documentation in the Gollum wiki states that slash characters within a link token will be converted to a hyphen when resolved to an HREF.  For example:

```
[[Backup / Recovery]]  ->  http://wiki/Backup---Recovery
```

In actual fact (testing against version `4.2.1`) the following conversion occurs:

```
[[Backup / Recovery]]  ->  http://wiki/Backup-/-Recovery
```

Unless the documentation is incorrect (I understand it is within a different Github project), then this would appear to be a bug.  (Or was this a page related to subpage handling?)

https://github.com/gollum/gollum/wiki#linking-internal-pages

**Comment by dometto** [comment]
Thanks for the report. Starting from `5.x`, gollum will not perform such substitution anymore. Slashes in file names will/should not be allowed (`Backup/Recovery` will be interpreted as pointing to a file under the `Recovery` directory).
