### ISSUE TITLE
New release with relaxed deps

### ISSUE THREAD

**Issue by mrueg** [gollum/gollum-lib#224]
I'd be interested in a new release, that includes https://github.com/gollum/gollum-lib/commit/9a437e4364819cb7ec9c58e7c78e74f69173e412 . Would that be possible?

Thanks!

**Comment by mrueg** [comment]
Friendly ping @dometto @bartkamphorst

**Comment by dometto** [comment]
Sorry for the delay. Yes, I'll cut a new gem based on master ASAP. @bartkamphorst, because of https://github.com/gollum/gollum-lib/commit/d56f5c44adb188f1159c16320f9400985b90f1c2 I'll make it 4.2.2.

**Comment by bartkamphorst** [comment]
👍

**Comment by mrueg** [comment]
@dometto  thanks for taking care of it! :)

**Comment by mrueg** [comment]
@dometto do you know when you will have time for it?

**Comment by dometto** [comment]
Just released `v4.2.2`. Again, apologies for the long response time.

**Comment by mrueg** [comment]
Thanks a bunch!
