### ISSUE TITLE
Update gemojione to 3.x

### ISSUE THREAD

**Issue by connorshea** [gollum/gollum-lib#226]
Right now the gemspec locks [gemojione](https://github.com/jonathanwiesel/gemojione) to `~> 2.2`, it'd be nice to have 3.x support in gollum-lib.

The main problem is that there's no support for Ruby 1.9 in gemojione 3.0. Either 1.9 would need to be dropped or we could allow either 2.x/3.x and use separate gemfiles to run tests with gemojione 2.x and 3.x.

**Comment by bartkamphorst** [comment]
I think dropping Ruby 1.9 for the 5.x release of gollum certainly is an option. Do you agree @dometto ?

**Comment by svoop** [comment]
@connorshea I'll take care of this.

**Comment by svoop** [comment]
@connorshea Oh, didn't see the Ruby 1.9 constraint. IMO, it's no good to add unneccessary complexity to the code for the sake of supporting a Ruby which reached it's EOL almost two years ago. I'd rather couple the Emoji-Update to dropping Ruby 1.9 as @bartkamphorst suggested.

**Comment by dometto** [comment]
> I'd rather couple the Emoji-Update to dropping Ruby 1.9 as @bartkamphorst suggested.

👍

In that case, I propose to also get rid of [these lines](https://github.com/gollum/gollum/blob/master/lib/gollum.rb#L14-L16) :)

**Comment by svoop** [comment]
@dometto In order to prepare a PR for Gollum 5 with the update to gemojione 3: Are the branches `gollum-lib:gollum-lib-5.x` and `gollum:5.x` the baselines to use?

**Comment by dometto** [comment]
Correct, @svoop!

**Comment by svoop** [comment]
There you go, sorry for the delay. As expected, the jruby-19mode tests fail.

**Comment by connorshea** [comment]
@svoop can we close this now?

**Comment by svoop** [comment]
@connorshea i'd say yes
