### ISSUE TITLE
Gollum's overridden kramdown renderer does not allow markdown tables

### ISSUE THREAD

**Issue by lopopolo** [gollum/gollum-lib#227]
gollum-lib sets the Kramdown renderer to `markdown` instead of the default `kramdown` when it [overrides github-markup's kramdown renderer](https://github.com/gollum/gollum-lib/blob/2c747d5e4042df2164f25f120d8b911ea32fbf6e/lib/gollum-lib/markups.rb#L6)

The markdown renderer is strict and does not allow the table extension.

I've managed to get tables rendering with kramdown by adding the following to my config.ru:

```ruby
GitHub::Markup::Markdown::MARKDOWN_GEMS['kramdown'] = proc { |content|
  Kramdown::Document.new(content, :auto_ids => false).to_html
}
```

See also: https://github.com/gollum/gollum/issues/907

**Comment by dometto** [comment]
Thanks for letting us know about this possible fix. For `gollum 5.x`, we can decide whether or not to switch to 'default' kramdown.
