### ISSUE TITLE
Encoding::CompatibilityError when both folder and file have non-ascii character

### ISSUE THREAD

**Issue by nimag42** [gollum/gollum-lib#239]
Hello,
There's a bug when I try to edit a file whose name contains non-ascii character (utf-8) and this file is in a folder whose name also contains non-ascii character (for example : try to edit /àà/éé).

The problems is:

        Encoding::CompatibilityError:  incompatible character encodings: ASCII-8BIT and UTF-8:
        /var/lib/gems/2.1.0/gems/gollum-lib-4.2.2/lib/gollum-lib/page.rb:174:in `url_path'
        /var/lib/gems/2.1.0/gems/gollum-lib-4.2.2/lib/gollum-lib/page.rb:214:in `escaped_url_path'
        /home/wiki/gollum/lib/gollum/app.rb:296:in `block in <class:App>'

So, exploring a bit in the code, I managed to find that the error is on this block
```ruby
    def url_path
      path = if self.path.include?('/')
               self.path.sub(/\/[^\/]+$/, '/')
             else
               ' '
             end
      puts path.encoding # Added by me
      puts Page.cname(self.name, '-', '-').encoding # Added by me
      path << Page.cname(self.name, '-', '-')
      path
    end
```

With the debug I saw that path is encoded in ASCII-8BIT and Page.cname is encoded in UTF-8, thus throwing an error in the concatenation (I suppose so, but I maybe wrong, I don't know ruby at all)

I managed to get rid of this error by appending a force_encoding in "UTF-8"

```ruby
 path.force_encoding("utf-8") << Page.cname(self.name, '-', '-')
```

I'm not sending a PR because I don't know if this issue is specific to me or not (I'm using the gollum-lib and gollum compiled with freshly pulled sources, and rugged as the git adapter) and also because I don't know if my fix is not a really ugly hack.

Thank you.

**Comment by bartkamphorst** [comment]
Thanks. The gollum-lib codebase is currently riddled with `force_encoding` statements unfortunately. For `v.5.x` we're looking to make everything use utf-8 by default. Might be a while though as @dometto and I are both swamped at the moment.

**Comment by bartkamphorst** [comment]
This is resolved in gollum's `5.x` branch.
