### ISSUE TITLE
Search is broken if there's an image in the repo

### ISSUE THREAD

**Issue by nimag42** [gollum/gollum-lib#240]
Hi.

If there's an image in the repository, any research will result in an error "Invalid bytes in UTF-8".

This is caused because the search tries to encode line of files in utf-8 before trying to match a regexp, but as image are binary files, they can not be encoded.

It's line 170 in git_layer_rugged.rb

**Comment by gerwitz** [comment]
@nimag42: I've encountered this same problem. How did you resolve it?
