### ISSUE TITLE
[[_TOC_]] showing H1 item with blank value when {h1_title => true}

### ISSUE THREAD

**Issue by iyerusad** [gollum/gollum-lib#247]
Didn't see this in existing open issue so opening...

## h1_title is false
```
wiki_options = {                                                       
  :h1_title => false                          
}                                             
Precious::App.set(:wiki_options, wiki_options)
```
Result (as expected):
![image](https://cloud.githubusercontent.com/assets/25647368/24475742/25503966-148e-11e7-85ec-135ab0c26d84.png)

## h1_title is true
```
wiki_options = {                                                       
  :h1_title => true
}                                             
Precious::App.set(:wiki_options, wiki_options)
```
Result (renders a h1 item in TOC with blank value):
![image](https://cloud.githubusercontent.com/assets/25647368/24475823/67423162-148e-11e7-94ee-16d9dd18ac57.png)

**Comment by dometto** [comment]
Can't reproduce this on 5.x
