### ISSUE TITLE
Fileview doesn't show page file extensions

### ISSUE THREAD

**Issue by dometto** [gollum/gollum-lib#264]
In 5.x we've stopped surpressing file extensions, but the fileview doesn't seem to show them. Preferably we would fix this and have a different way of showing the difference between pages and files (in case of the 'all files' view).

**Comment by bartkamphorst** [comment]
Nice idea. 👍

**Comment by dometto** [comment]
This would still be an option for the new Overview page.

**Comment by dometto** [comment]
This is fixed on 5.x
