### ISSUE TITLE
GlobalTOC() Macro doesn't support base_path

### ISSUE THREAD

**Issue by Agilus** [gollum/gollum-lib#280]
If you start gollum with the --base_path option, giving you a wiki that is not at the root of a URL (e.g. http://myhost.com/subpathwiki instead of http://myhost.com/), the GlobalTOC() creates a list of links that point to the wrong place.  

Instead of pointing to http://myhost.com/subpathwiki/Home, a link made by GlobalTOC() will point to http://myhost.com/Home .

The fix for this problem is relatively simple, and I have it ready to commit.

**Comment by irstevenson** [comment]
Same issue (and by the looks of it, same fix need) with `Navigation()`.

**Comment by dometto** [comment]
Fixed in `v5.x`
