### ISSUE TITLE
plantuml filter doesn't work without modification

### ISSUE THREAD

**Issue by nkabir** [gollum/gollum-lib#289]
Note that I needed to modify `gen_url`  for Gollum to correctly generate PlantUML diagrams:

```
  # Compression code used to generate PlantUML URLs. Taken directly from the
  # Transcoder class in the PlantUML java code.
  def gen_url(text)
    result = ""

    zlibbed = Zlib::Deflate.deflate(text)
    compressedData = zlibbed[2..-5]

    compressedData.chars.each_slice(3) do |bytes|
      #print bytes[0], ' ' , bytes[1] , ' ' , bytes[2]
      b1 = bytes[0].nil? ? 0 : (bytes[0].ord & 0xFF)
      b2 = bytes[1].nil? ? 0 : (bytes[1].ord & 0xFF)
      b3 = bytes[2].nil? ? 0 : (bytes[2].ord & 0xFF)
      result += append3bytes(b1, b2, b3)
    end
    "#{server_url}/#{result}"
  end

```
Otherwise the service returns the placeholder image

![plantuml](https://user-images.githubusercontent.com/92801/34502713-649099b8-efda-11e7-8b7c-dfda4a17219a.png)

**Comment by bartkamphorst** [comment]
Could you show an example of a diagram that produces the placeholder image? Because when I add [this example from the wiki](https://github.com/gollum/gollum/wiki#plantuml-diagrams) to a page the diagram renders without a hitch without needing this line `compressedData = zlibbed[2..-5]`.

**Comment by bartkamphorst** [comment]
This issue will be fixed in `5.x` release. See [here](https://github.com/gollum/gollum/issues/1279) for a quickfix.
