### ISSUE TITLE
Set commit date on committing changes

### ISSUE THREAD

**Issue by Dahie** [gollum/gollum-lib#373]
Hi, 

I'm working on a software to convert database-based legacy wiki systems into gollum git-repositories [Caramelize](https://github.com/Dahie/caramelize/). I manage to persist the history, but not the date of the changes, which I'd like to see reflected in the commit dates of the git repository. I don't see how I can pass this as a parameter in the `Committer`. Am I missing something? Where can this option be added?

Thank you :)

**Comment by dometto** [comment]
Thanks for working on caramelize! Cool project :) It may be nice to add some info about it to the gollum documentation?

You're right that gollum-lib doesn't allow you to pass in an arbitrary date when creating a commit. But worse: the underlying git libraries don't seem to support such an operation. See for instance Rugged's commit creation method, which does not have a parameter for date:

https://www.rubydoc.info/gems/rugged/Rugged/Commit#create-class_method

Apparently the assumed behavior is just to use `Time.now`. Perhaps as a workaround, you could use `git commit --amend --no-edit` ([here](https://codewithhugo.com/change-the-date-of-a-git-commit/)) to achieve the desired result after the commits have been created? It would have to use a command line call, or [grit](https://gitlab.com/gitlab-org/gitlab-grit/tree/master). :( But since I don't see a way of doing this with rugged, I don't see a way of doing it with gollum-lib, either.

You could also check if JGit lets use do this, although that would mean Caramelize would have to use JRuby.

**Comment by Dahie** [comment]
Hi, I see. So far I used a monkey-patched grit-adapter, but I had constant encoding issues and I was kind of relieved to move away from that. I have to sleep about it, maybe I find something in rugged to hook into.

Where do you mean I should add caramelize to the documentation?

**Comment by dometto** [comment]
Maybe add a page or a section about caramelize in the [wiki](https://github.com/gollum/gollum/wiki)?

Good luck, I understand getting away from `grit` would be good. Let us know if we can help with anything.

Just FYI: it looks JGit at least [has this ability under the hood](https://archive.eclipse.org/jgit/site/5.1.0.201809111528-r/apidocs/). Maybe rugged can pull it off, as well.

**Comment by bartkamphorst** [comment]
@Dahie It would seem that it is possible in Rugged. I haven't tested this, but if you look at the example of `Commit.amend` given [here](https://www.rubydoc.info/github/libgit2/rugged/Rugged%2FCommit:amend) you see that the author hash takes a `:time` key. With any luck that timestamp is used for the amended commit.

**Comment by bartkamphorst** [comment]
Just tested this, and yes, it appears to work 👍 :
```ruby
require 'rugged'
require 'time'

path = "../gollum-wiki"
sha = "62f6fcbba63342bb6e607353d66523b3728807d1"
r = Rugged::Repository.new(path)
c = r.lookup(sha)
author = c.author
author[:time] = Time.parse('2009-05-01 10:30:22')
c.amend(author: author, message: 'updated time commit', committer: author, tree: c.tree)
 # => "1289d8e0b6aaacfca64e19a8a391cda288b89192"
```

And, just to double-check:
```sh
gollum-wiki $ git show "1289d8e0b6aaacfca64e19a8a391cda288b89192"
commit 1289d8e0b6aaacfca64e19a8a391cda288b89192
Author: Anonymous
Date:   Fri May 1 10:30:22 2009 +0200

    updated time commit

**Comment by Dahie** [comment]
Awesome! Thank you, I'll check it out tomorrow!

**Comment by bartkamphorst** [comment]
You're welcome. And, for the record, the same trick also applies to `Rugged::Commit#create`:
```ruby
author = {name: "Anonymous", email: "anon@example.com", time: Time.parse('2009-05-01 10:30:22')}
 Rugged::Commit.create(r, author: author, message: 'create backdated commit', committer: author, parents: [], tree: c.tree)
 => "fe0dcf3b7b78bd933ffc100a1cd1f049d6d3a17f" 
```

```sh
git show "fe0dcf3b7b78bd933ffc100a1cd1f049d6d3a17f"
commit fe0dcf3b7b78bd933ffc100a1cd1f049d6d3a17f
Author: Anonymous 
Date:   Fri May 1 10:30:22 2009 +0200

    create backdated commit

**Comment by bartkamphorst** [comment]
Similarly, in `JGit`, as @dometto suggested, this appears to be possible by adding a date to the `PersonIdent` constructor that is passed to `CommitCommand#setCommitter`. See [here](https://stackoverflow.com/questions/51150709/how-to-set-the-commit-time-with-jgit) for the example and [here](https://download.eclipse.org/jgit/site/5.1.1.201809181055-r/apidocs/org/eclipse/jgit/lib/PersonIdent.html) for the `PersonIdent` constructor(s).

**Comment by dometto** [comment]
Nice find @bartkamphorst! @Dahie if you want to try and add this option to `gollum-lib` (not sure if you need that for your project) we'll be happy to advise.

**Comment by Dahie** [comment]
Thanks, I take you up the offer. I'd like to add `time` as an optional attribute to `Gollum::Git::Actor`. Adding it to `adapter_specs`, `rjgit_adapter` and `rugged_adapter`, and to `Gollum::Committer#actor` to pass a commit time via the options hash into the new actor. Does that sound like a plan? Are there any things I should pay attention to?

**Comment by dometto** [comment]
That sounds exactly like what needs to be done. :) I think RJGit doesn't yet support adding a time to an Actor object, but we could work on that.

I suspect you'll also want to add support for time in [this method](https://github.com/gollum/gollum-lib/blob/master/lib/gollum-lib/committer.rb#L56). Then you could initialize a Committer with `:time` in the options hash.

**Comment by Dahie** [comment]
That's what I had in my mind. Alright, I'll post a few PR's later today.
