### ISSUE TITLE
Make dependency on twitter optional

### ISSUE THREAD

**Issue by harleypig** [gollum/gollum-lib#399]
Can you make the dependency on twitter-text optional? I don't use twitter for anything (I canceled my account 3 years ago).

**Comment by dometto** [comment]
https://github.com/twitter/twitter-text is just a library that gollum uses for things like autolinking (generating html `<a>` tags for strings that look like a link) and handling text encoding. It in no way constitutes a connection to twitter.com, and gollum does not (and will never) include things like tweet buttons or anything else that would involve twitter tracking.
