### ISSUE TITLE
markups @master still referring to python2 for rst support

### ISSUE THREAD

**Issue by patrickdung** [gollum/gollum-lib#404]
Hello,

Regarding https://github.com/gollum/gollum/issues/1548#issuecomment-611378586.
github-mark 4.0 is updated to use Python 3. But the gollum-lib/markups.rb (Line 84) is still looking for python2.

In a Docker setup that it only have Python 3, I had to update that rb file to change it from python2 to python3.

```
             :enabled => MarkupRegisterUtils::executable_exists?("python2"),
```
Thanks.

**Comment by dometto** [comment]
Thanks for letting us know!

**Comment by dometto** [comment]
Fixed in https://github.com/gollum/gollum-lib/pull/405. I'll do a bugfix release now.
